[package]
name = "FinSc-Electromagnetism-Wiki"
version = "0.3.0"
ipkg = "FinSc-Electromagnetism-Wiki.ipkg"

[custom.all.FinSc-Electromagnetism-Wiki]
type = "local"
path = "."
ipkg = "FinSc-Electromagnetism-Wiki.ipkg"

[custom.all.FinSc-Electromagnetism]
type = "local"
path = "../FinSc-Electromagnetism"
ipkg = "FinSc-Electromagnetism.ipkg"

[custom.all.FinSc-Multiset-Core]
type = "local"
path = "../FinSc-Multiset-Core"
ipkg = "FinSc-Multiset-Core.ipkg"

[custom.all.FinSc-Multiset-Transform]
type = "local"
path = "../FinSc-Multiset-Transform"
ipkg = "FinSc-Multiset-Transform.ipkg"

[custom.all.FinSc-Geometry]
type = "local"
path = "../FinSc-Geometry"
ipkg = "FinSc-Geometry.ipkg"

[custom.all.FinSc-Dihedron]
type = "local"
path = "../FinSc-Dihedron"
ipkg = "FinSc-Dihedron.ipkg"

[custom.all.FinSc-Fields]
type = "local"
path = "../FinSc-Fields"
ipkg = "FinSc-Fields.ipkg"

[custom.all.idris2-QuickCheck]
type = "local"
path = "../idris2-QuickCheck"
ipkg = "idris2-QuickCheck.ipkg"
